SELECT NAME, DATETIME
FROM (SELECT a.NAME, a.DATETIME
    FROM ANIMAL_INS a LEFT OUTER JOIN ANIMAL_OUTS o
    ON a.ANIMAL_ID = o.ANIMAL_ID
    WHERE o.DATETIME IS NULL
    ORDER BY a.DATETIME)
WHERE ROWNUM <= 3