SELECT mp.MEMBER_NAME, rr.REVIEW_TEXT, TO_CHAR(rr.REVIEW_DATE, 'YYYY-MM-DD') as REVIEW_DATE
FROM MEMBER_PROFILE mp INNER JOIN REST_REVIEW rr
ON mp.MEMBER_ID = rr.MEMBER_ID
WHERE mp.MEMBER_ID IN 
(
    SELECT rr.MEMBER_ID
    FROM REST_REVIEW rr
    GROUP BY rr.MEMBER_ID
    HAVING COUNT(*) = 
    (
        SELECT MAX(COUNT(*))
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    )
)
ORDER BY rr.REVIEW_DATE ASC, rr.REVIEW_TEXT ASC
