SELECT DISTINCT c1.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c1 JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY c2
ON c1.CAR_ID = c2.CAR_ID
WHERE c1.CAR_TYPE = '세단'
AND TO_CHAR(c2.start_date,'YYYYMM') = '202210'
ORDER BY c1.CAR_ID DESC;