SELECT fi.ID, fni.FISH_NAME, fi.LENGTH
FROM FISH_INFO as fi 
JOIN FISH_NAME_INFO as fni ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE fi.LENGTH = (SELECT MAX(LENGTH)
                  FROM FISH_INFO
                  WHERE FISH_TYPE = fi.FISH_TYPE)
ORDER BY fi.ID asc;