SELECT hd.DEPT_ID, hd.DEPT_NAME_EN, ROUND(AVG(he.sal), 0) as AVG_SAL
FROM HR_DEPARTMENT hd
INNER JOIN HR_EMPLOYEES he ON hd.DEPT_ID = he.DEPT_ID
GROUP BY hd.DEPT_ID, hd.DEPT_NAME_EN
ORDER BY AVG_SAL DESC;